version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./go-react/static:/static

    depends_on:
      - demo-web

    expose:
      - "80"

    ports:
      - "7878:80"
  demo-web:
    build:
      context: ./go-rust

    expose:
      - "8080"

    container_name: demo-web

  node:
    build:
      context: ./go-react

    command: "npx webpack --watch true"

    volumes:
      - /usr/src/app/node_modules/
      - ./go-react:/usr/src/app
